version: "3"

services:
  web:
    container_name: "web"
    build: nginx
    ports:
      - "8000:80"
    volumes:
      - ./app/conf.d:/etc/nginx/conf.d
    networks:
      - django_network
    depends_on:
      - backend

  backend:
    build: backend
    container_name: "backend"
    command: poetry run gunicorn config.wsgi:application --bind 0.0.0.0:8000
    restart: unless-stopped
    env_file:
      - backend/.env
    expose:
      - 8000
    depends_on:
      - db
    networks:
      - django_network

  db:
    build: db
    restart: always
    container_name: "db"
    env_file:
      - backend/.env
    ports:
      - "5433:5432"
    networks:
      - django_network

networks:
  django_network:
    driver: bridge
