# Generated by Django 4.1.5 on 2023-01-27 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sheets", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="sheet",
            old_name="file",
            new_name="file_pdf",
        ),
    ]
