# Generated by Django 4.1.5 on 2023-01-27 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sheets", "0002_rename_file_sheet_file_pdf"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sheet",
            name="tags",
            field=models.ManyToManyField(related_name="post", to="sheets.tag"),
        ),
    ]
