# Generated by Django 4.1.5 on 2023-01-27 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sheets", "0003_alter_sheet_tags"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sheet",
            name="tags",
            field=models.ManyToManyField(
                blank=True, related_name="post", to="sheets.tag"
            ),
        ),
    ]
