# Generated by Django 4.1.5 on 2023-01-27 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sheets", "0004_alter_sheet_tags"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sheet",
            name="photo",
            field=models.ImageField(max_length=200, upload_to=""),
        ),
    ]
