# Generated by Django 4.1.5 on 2023-01-27 07:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("sheets", "0005_alter_sheet_photo"),
    ]

    operations = [
        migrations.RenameField(
            model_name="category",
            old_name="author",
            new_name="user",
        ),
        migrations.RenameField(
            model_name="tag",
            old_name="author",
            new_name="user",
        ),
        migrations.AddField(
            model_name="sheet",
            name="user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
