# Generated by Django 4.1.5 on 2023-01-27 07:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("sheets", "0006_rename_author_category_user_rename_author_tag_user_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="author",
            name="user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
