name: Run Tests


on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_DB: ${{ secrets.POSTGRES_NAME }}
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v2
      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.10.6
      - name: Install Deps
        working-directory: ./backend
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run tests
        working-directory: ./backend
        run: |
          touch .env   
          echo SECRET_KEY='${{ secrets.SECRET_KEY }}' >> .env
          echo DEBUG='${{ secrets.DEBUG }}' >> .env
          echo ALLOWED_HOSTS='${{ secrets.ALLOWED_HOSTS }}' >> .env
          echo POSTGRES_NAME='${{ secrets.POSTGRES_NAME }}' >> .env
          echo POSTGRES_USER='${{ secrets.POSTGRES_USER }}' >> .env
          echo POSTGRES_PASSWORD='${{ secrets.POSTGRES_PASSWORD }}' >> .env
          echo DB_HOST='${{ secrets.DB_HOST }}' >> .env
          echo DB_PORT='${{ secrets.DB_PORT }}' >> .env
          cat .env
          make test
