name: Run Code Checks


on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # Install Python
      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.10.6
      # Update pip and install all requirements
      - name: Install Deps
        working-directory: ./backend
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      # Check problems with linters
      - name: Run all linters
        working-directory: ./backend
        run: make format
