name: Run Tests


on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Python
        working-directory: ./backend
        uses: actions/setup-python@v2
        with:
          python-version: 3.11
      - name: Install Deps
        working-directory: ./backend
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run tests
        working-directory: ./backend
        run: |
          python manage.py test
